# Instruction


import requests
import json
import os
import datetime
import calendar
import urllib
from flask import Flask, request, jsonify


class Bamboohr:
    def __init__(self):
        self.companyDomain = os.environ['COMPANY_DOMAIN']
        self.AUTHORIZATION_TOKEN = os.environ['AUTHORIZATION_TOKEN']
        self.status = {
            'approve': 'approved',
            'decline': 'declined',
            'request': 'requested'
        }

    def get_employee_directory(self):
        url = f"https://api.bamboohr.com/api/gateway.php/{self.companyDomain}/v1/employees/directory"
        headers = {
            "accept": "application/json",
            # authorization is generated by feeding API key to code snippet
            "authorization": f"Basic {self.AUTHORIZATION_TOKEN}"
        }
        response = requests.request("GET", url, headers=headers)
        response_parse = json.loads(response.text)
        if response.status_code == 200:
            return response_parse
        else:
            # print(response)
            return {}

    # method in class doesnt allow empty arg - put 'self'
    # if there are more than 2 args, put 'self' as the 1st arg

    def get_employee(self, employee_id):
        url = f"https://api.bamboohr.com/api/gateway.php/{self.companyDomain}/v1/employees/{employee_id}/"
        querystring = {"fields": "firstName,lastName"}
        headers = {
            "accept": "application/json",
            "authorization": f"Basic {self.AUTHORIZATION_TOKEN}"
        }
        response = requests.request(
            "GET", url, headers=headers, params=querystring)
        response_parse = json.loads(response.text)
        if response.status_code == 200:
            return response_parse
        else:
            print(response)
            return {}

    # Get time of balance
    def time_off_balance(self, employee_id):
        url = f"https://api.bamboohr.com/api/gateway.php/{self.companyDomain}/v1/employees/{employee_id}/time_off/calculator"
        headers = {
            "accept": "application/json",
            "authorization": f"Basic {self.AUTHORIZATION_TOKEN}"
        }
        response = requests.request(
            "GET", url, headers=headers)

        # Solution2 : use urllib.parse.parse_qs
        # parse JSON response.text, return type 'list'
        response_parse_tolist = json.loads(response.text)
        # print(response_parse_tolist)

        # convert a list of dictionaries into a dict
        response_todict = {}
        for item in response_parse_tolist:
            # print(item)
            # print("----------")
            # remove and return the name field to use as a key
            name = item.pop("name")
            # add new key:value to response_todict Dict
            response_todict[name] = item
        # print(response_todict)

        # Expected: collect "time off type": {'balance': '..', 'usedYearToDate': '..', 'end': '...'}
        answer = {}
        # collect all keys from response_todict ("Vacation", "Sick", "COVID-19 Related Absence", "Bereavement", "Comp/In Lieu Time", "FMLA")
        keys = response_todict.keys()
        info_needed = ("balance", "usedYearToDate", "end")
        # Go to (e.g) "Vacation":{'timeOffType': '78', 'units': 'hours', 'balance': '0.0', 'end': '2020-09-24', 'policyType': 'discretionary', 'usedYearToDate': '32.0'}
        for key in keys:
            sub_answer = {}
            # Check if the element is info_needed
            # For each element in value of key "Vaction"
            for el in response_todict[key]:
                # Create a sub-dict inside answer Dict  {'Vacation': {}, 'Sick': {}, ...}
                if el in info_needed:
                    # add el key:value to sub_answer dict
                    # 'Vacation': {'balance': '0.0', 'end': '2020-09-24'...}
                    sub_answer[el] = response_todict[key][el]
            # add sub_answer Dict to answer Dict
            # {'Vacation': {'balance': '0.0', 'end': '2020-09-24', 'usedYearToDate': '0.0'}, 'Sick': {'balance': '0.0', 'end': '2020-09-24', 'usedYearToDate': '0.0'}, ...}
            answer[key] = sub_answer

        # return result to answer user
        if response.status_code == 200:
            # print(answer)
            # sample answer
            # {'Vacation': {'balance': '81.0', 'end': '2020-09-26', 'usedYearToDate': '144.0'},'Sick': {'balance': '0.0', 'end': '2020-09-26', 'usedYearToDate': '0.0'},...}
            return answer
        else:
            return answer

    # Get time off policies
    def time_off_policy(self):
        url = f"https://api.bamboohr.com/api/gateway.php/{self.companyDomain}/v1/meta/time_off/policies/"
        headers = {
            "accept": "application/json",
            "authorization": f"Basic {self.AUTHORIZATION_TOKEN}"}
        response = requests.request("GET", url, headers=headers)
        # parse JSON response.text, return a list of dictionaries
        response_parse_tolist = json.loads(response.text)

        # convert a list of dictionaries into a dict
        response_todict = {}
        for item in response_parse_tolist:
            # remove and return the name field to use as a key
            name = item.pop("name")
            # add new key:value to response_todict Dict
            response_todict[name] = item

        # Expected: collect "policy'": {'id': '..', 'effectiveDate': '..'}
        answer = {}
        # collect all keys from response_todict ("BambooHR Manual Policy", "Vacation Full-Time", ..)
        keys = response_todict.keys()
        info_needed = ("id", "effectiveDate")

        # Go to (e.g) 'BambooHR Manual Policy': {'id': '82', 'timeOffTypeId': '82', 'effectiveDate': None, 'type': 'manual'}
        for key in keys:
            # Create a sub-dict inside answer Dict  {"BambooHR Manual Policy": {}, "Vacation Full-Time": {}, ...}
            sub_answer = {}
            # For each element in value of key "BambooHR Manual Policy"
            for el in response_todict[key]:
                # Check if the element is info_needed
                if el in info_needed:
                    # add el key:value to sub_answer dict
                    # 'BambooHR Manual Policy': {'id': '..', 'effectiveDate': '..'}
                    sub_answer[el] = response_todict[key][el]
            # add sub_answer Dict to answer Dict
            # {'BambooHR Manual Policy': {'id': '..', 'effectiveDate': '..'}, ...}
            answer[key] = sub_answer

        if response.status_code == 200:
            # print(answer)
            # answer sample
            # {'BambooHR Manual Policy': {'id': '81', 'effectiveDate': None},.....}
            return answer
        else:
            return {}

    # Request time off

    def time_off_request(self, employee_id, start_date, end_date, amount, timeOffTypeId, note):
        url = f"https://api.bamboohr.com/api/gateway.php/{self.companyDomain}/v1/employees/{employee_id}/time_off/request"
        headers = {
            "content-type": "application/json",
            "authorization": f"Basic {self.AUTHORIZATION_TOKEN}"
        }
        payload = {
            "notes": [
                {
                    "from": "employee",
                    "note": f"{note}"
                }
            ],
            "status": f'{self.status["request"]}',
            "start": f'{start_date}',
            "end": f'{end_date}',
            "timeOffTypeId": f'{timeOffTypeId}',
            "amount": f'{amount}'
        }
        response = requests.request("PUT", url, json=payload, headers=headers)
        # print(response.status_code)
        if response.status_code == 201:
            return 'requested'

    def get_request_id(self, employee_id):
        start = datetime.date.today()
        end = self.get_month_day_range(start)
        url = f"https://api.bamboohr.com/api/gateway.php/{self.companyDomain}/v1/time_off/requests/"

        querystring = {"employeeId": f"{employee_id}", "start": f"{start}",
                       "end": f"{end}", "status": "requested"}
        headers = {
            "accept": "application/json",
            "authorization": f"Basic {self.AUTHORIZATION_TOKEN}"
        }
        response = requests.request(
            "GET", url, headers=headers, params=querystring)
        check = json.loads(response.text)
        print(check[-1])
        print(type(check))

    # https://gist.github.com/waynemoore/1109153
    def get_month_day_range(self, date):
        # For a date 'date' returns the start and end date for the month of 'date'.

        # Month with 31 days:
        # >>> date = datetime.date(2011, 7, 27)
        # >>> get_month_day_range(date)
        # (datetime.date(2011, 7, 1), datetime.date(2011, 7, 31))

        # Month with 28 days:
        # >>> date = datetime.date(2011, 2, 15)
        # >>> get_month_day_range(date)
        # (datetime.date(2011, 2, 1), datetime.date(2011, 2, 28))

        # first_day = date.replace(day=1)
        last_day = date.replace(
            day=calendar.monthrange(date.year, date.month)[1])
        return last_day


# Instantiate class Bamboohr
bamboohr = Bamboohr()

if __name__ == "__main__":
    # bamboohr.get_employee_directory()
    # bamboohr.get_employee()
    # bamboohr.time_off_balance(108)
    # bamboohr.time_off_policy()
    # bamboohr.time_off_request(108, '2020-10-10', '2020-10-12', 3, 78, 'hello')
    bamboohr.get_request_id(108)
    # bamboohr.get_month_day_range(datetime.date.today())
